/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package san.jmat.view.render.panel.pack;

import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.CoverUpImageTransition;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.MouseEvent;
import san.jmat.controler.ControllerAccessories;
import san.jmat.program.Form;
import san.jmat.view.render.panel.button.Button2;

/**
 *
 * @author wannabe
 */
public class Accessories extends javax.swing.JPanel {
    private Form form;
    private ControllerAccessories controllerAccessories;
    
    /**
     * Creates new form Accessories
     */
    public Accessories() {
        initComponents();
        
    }

    public Button2 getBtnKalkulator() {
        return btnKalkulator;
    }

    public Button2 getBtnMath() {
        return btnMath;
    }

    public Button2 getBtnNotepad() {
        return btnNotepad;
    }

    public Button2 getBtnNotes() {
        return btnNotes;
    }

    public Button2 getBtnPaint() {
        return btnPaint;
    }

    public Button2 getBtnRecorder() {
        return btnRecorder;
    }

    public Button2 getBtnWordPad() {
        return btnWordPad;
    }

    public void setForm(Form form) {
        this.form = form;
    }

    public void setControllerAccessories(ControllerAccessories controllerAccessories) {
        this.controllerAccessories = controllerAccessories;
    }

    
    public void disableButton(boolean calc, boolean mathInput,boolean notepad,boolean notes,boolean paint,boolean recorder,boolean wordpad){
        btnKalkulator.setVisible(calc);
        menuCalc.setVisible(calc);
        btnMath.setVisible(mathInput);
        menuMath.setVisible(mathInput);
        btnNotepad.setVisible(notepad);
        menuNotepad.setVisible(notepad);
        btnNotes.setVisible(notes);
        menuNotes.setVisible(notes);
        btnPaint.setVisible(paint);
        menuMSPaint.setVisible(paint);
        btnRecorder.setVisible(recorder);
        menuRecorder.setVisible(recorder);
        btnWordPad.setVisible(wordpad);
        menuWordPad.setVisible(wordpad);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popRenderAccessories1 = new san.jmat.view.render.panel.popRender.popRenderAccessories();
        menuJMat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCalc = new javax.swing.JMenuItem();
        menuNotepad = new javax.swing.JMenuItem();
        menuMSPaint = new javax.swing.JMenuItem();
        menuMath = new javax.swing.JMenuItem();
        menuWordPad = new javax.swing.JMenuItem();
        menuNotes = new javax.swing.JMenuItem();
        menuRecorder = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuBack = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnKalkulator = new san.jmat.view.render.panel.button.Button2();
        btnNotepad = new san.jmat.view.render.panel.button.Button2();
        btnPaint = new san.jmat.view.render.panel.button.Button2();
        btnMath = new san.jmat.view.render.panel.button.Button2();
        btnWordPad = new san.jmat.view.render.panel.button.Button2();
        btnNotes = new san.jmat.view.render.panel.button.Button2();
        btnRecorder = new san.jmat.view.render.panel.button.Button2();

        popRenderAccessories1.setBackground(new java.awt.Color(153, 153, 255));

        menuJMat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuJMat.setText("Java Master");
        popRenderAccessories1.add(menuJMat);
        popRenderAccessories1.add(jSeparator2);

        menuCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Utilities-calculator-icon6.png"))); // NOI18N
        menuCalc.setText("Calculator");
        menuCalc.setToolTipText("Calculator");
        menuCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalcActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuCalc);

        menuNotepad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Notepad-iconr.png"))); // NOI18N
        menuNotepad.setText("Notepad");
        menuNotepad.setToolTipText("Notepad");
        menuNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotepadActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuNotepad);

        menuMSPaint.setText("Paint");
        menuMSPaint.setToolTipText("MS Paint");
        menuMSPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMSPaintActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuMSPaint);

        menuMath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Mimetypes-application-vnd-stardivision-math-icon7.png"))); // NOI18N
        menuMath.setText("Math Input Panel");
        menuMath.setToolTipText("Math Input Panel");
        menuMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMathActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuMath);

        menuWordPad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Wordpad-icon7.png"))); // NOI18N
        menuWordPad.setText("WordPad");
        menuWordPad.setToolTipText("WordPad");
        menuWordPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWordPadActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuWordPad);

        menuNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/task-notes-icon6.png"))); // NOI18N
        menuNotes.setText("Notes");
        menuNotes.setToolTipText("Notes");
        menuNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotesActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuNotes);

        menuRecorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/recorder-icon7.png"))); // NOI18N
        menuRecorder.setText("Sound Recorder");
        menuRecorder.setToolTipText("Sound Recorder");
        menuRecorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecorderActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuRecorder);
        popRenderAccessories1.add(jSeparator1);

        menuBack.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Misc-Back-icon2.png"))); // NOI18N
        menuBack.setText("Back To Dekstop Menu");
        menuBack.setActionCommand("Back To Menu");
        menuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBackActionPerformed(evt);
            }
        });
        popRenderAccessories1.add(menuBack);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 106, 182));
        jLabel1.setText("Accessories");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        btnKalkulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Utilities-calculator-icon.png"))); // NOI18N
        btnKalkulator.setToolTipText("Calculator");
        btnKalkulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKalkulatorActionPerformed(evt);
            }
        });

        btnNotepad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Notepad-icon2.png"))); // NOI18N
        btnNotepad.setToolTipText("Notepad");
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });

        btnPaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/23_jetaudio.png"))); // NOI18N
        btnPaint.setToolTipText("Paint");
        btnPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaintActionPerformed(evt);
            }
        });

        btnMath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Mimetypes-application-vnd-stardivision-math-icon2.png"))); // NOI18N
        btnMath.setToolTipText("Math Input Panel");
        btnMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathActionPerformed(evt);
            }
        });

        btnWordPad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/Wordpad-icon2.png"))); // NOI18N
        btnWordPad.setToolTipText("WordPad");
        btnWordPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordPadActionPerformed(evt);
            }
        });

        btnNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/task-notes-icon1.png"))); // NOI18N
        btnNotes.setToolTipText("Notes");
        btnNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotesActionPerformed(evt);
            }
        });

        btnRecorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/accsessories/recorder-icon2.png"))); // NOI18N
        btnRecorder.setToolTipText("Sound Recorder");
        btnRecorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNotepad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnMath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWordPad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotepad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWordPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==MouseEvent.BUTTON3){
            popRenderAccessories1.show((Component)evt.getSource(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void menuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBackActionPerformed
        // TODO add your handling code here:
        CoverUpImageTransition transition=new CoverUpImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "Menu Dekstop");
    }//GEN-LAST:event_menuBackActionPerformed

    private void btnKalkulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKalkulatorActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runAplSystem32("calc.exe");
        
    }//GEN-LAST:event_btnKalkulatorActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runAplSystem32("notepad.exe");
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaintActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runAplSystem32("mspaint.exe");
    }//GEN-LAST:event_btnPaintActionPerformed

    private void btnMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runApl("mip.exe");
    }//GEN-LAST:event_btnMathActionPerformed

    private void btnRecorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorderActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runAplSystem32("SoundRecorder.exe");
    }//GEN-LAST:event_btnRecorderActionPerformed

    private void btnNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotesActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runAplSystem32("StikyNot.exe");
    }//GEN-LAST:event_btnNotesActionPerformed

    private void btnWordPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordPadActionPerformed
        // TODO add your handling code here:
        controllerAccessories.runApl("wordpad.exe");
    }//GEN-LAST:event_btnWordPadActionPerformed

    private void menuCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalcActionPerformed
        // TODO add your handling code here:
        btnKalkulatorActionPerformed(evt);
    }//GEN-LAST:event_menuCalcActionPerformed

    private void menuNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotepadActionPerformed
        // TODO add your handling code here:
        btnNotepadActionPerformed(evt);
    }//GEN-LAST:event_menuNotepadActionPerformed

    private void menuMSPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMSPaintActionPerformed
        // TODO add your handling code here:
        btnPaintActionPerformed(evt);
    }//GEN-LAST:event_menuMSPaintActionPerformed

    private void menuMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMathActionPerformed
        // TODO add your handling code here:
        btnMathActionPerformed(evt);
    }//GEN-LAST:event_menuMathActionPerformed

    private void menuWordPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWordPadActionPerformed
        // TODO add your handling code here:
        btnWordPadActionPerformed(evt);
    }//GEN-LAST:event_menuWordPadActionPerformed

    private void menuNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotesActionPerformed
        // TODO add your handling code here:
        btnNotesActionPerformed(evt);
    }//GEN-LAST:event_menuNotesActionPerformed

    private void menuRecorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecorderActionPerformed
        // TODO add your handling code here:
        btnRecorderActionPerformed(evt);
    }//GEN-LAST:event_menuRecorderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.view.render.panel.button.Button2 btnKalkulator;
    private san.jmat.view.render.panel.button.Button2 btnMath;
    private san.jmat.view.render.panel.button.Button2 btnNotepad;
    private san.jmat.view.render.panel.button.Button2 btnNotes;
    private san.jmat.view.render.panel.button.Button2 btnPaint;
    private san.jmat.view.render.panel.button.Button2 btnRecorder;
    private san.jmat.view.render.panel.button.Button2 btnWordPad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuBack;
    private javax.swing.JMenuItem menuCalc;
    private javax.swing.JMenuItem menuJMat;
    private javax.swing.JMenuItem menuMSPaint;
    private javax.swing.JMenuItem menuMath;
    private javax.swing.JMenuItem menuNotepad;
    private javax.swing.JMenuItem menuNotes;
    private javax.swing.JMenuItem menuRecorder;
    private javax.swing.JMenuItem menuWordPad;
    private san.jmat.view.render.panel.popRender.popRenderAccessories popRenderAccessories1;
    // End of variables declaration//GEN-END:variables
}
