/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package san.jmat.view.render.panel.pack;

import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.FadeImageTransition;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import san.jmat.controler.ControllerAudio;
import san.jmat.program.Form;
import san.jmat.view.render.panel.button.Button2;

/**
 *
 * @author wannabe
 */
public class Audio extends javax.swing.JPanel {
    private Form form;
    private ControllerAudio controllerAudio;
    /**
     * Creates new form Audio
     */
    public Audio() {
        initComponents();
        btnWinamp.setVisible(false);
        btnAimp.setVisible(false);
        btnJetaudio.setVisible(false);
        
        menuWinamp.setVisible(false);
        menuAimp.setVisible(false);
        menuJetaudio.setVisible(false);
    }

    public void setForm(Form form) {
        this.form = form;
    }

    public Button2 getBtnWinamp() {
        return btnWinamp;
    }

    public Button2 getBtnAimp() {
        return btnAimp;
    }

    public Button2 getBtnJetaudio() {
        return btnJetaudio;
    }

    public JMenuItem getMenuAimp() {
        return menuAimp;
    }

    public JMenuItem getMenuJetaudio() {
        return menuJetaudio;
    }

    public JMenuItem getMenuWinamp() {
        return menuWinamp;
    }

    public void setControllerAudio(ControllerAudio controllerAudio) {
        this.controllerAudio = controllerAudio;
    }

   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popRenderAudio1 = new san.jmat.view.render.panel.popRender.popRenderAudio();
        menuJMat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuWinamp = new javax.swing.JMenuItem();
        menuAimp = new javax.swing.JMenuItem();
        menuJetaudio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuBackToMenu = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnWinamp = new san.jmat.view.render.panel.button.Button2();
        btnAimp = new san.jmat.view.render.panel.button.Button2();
        btnJetaudio = new san.jmat.view.render.panel.button.Button2();

        menuJMat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuJMat.setText("Java Master");
        popRenderAudio1.add(menuJMat);
        popRenderAudio1.add(jSeparator2);

        menuWinamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/audio/Winamp-icon2.png"))); // NOI18N
        menuWinamp.setText("Winamp");
        popRenderAudio1.add(menuWinamp);

        menuAimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/audio/aimp-icon2.png"))); // NOI18N
        menuAimp.setText("Aimp2");
        popRenderAudio1.add(menuAimp);

        menuJetaudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/audio/JetAudio-icon2.png"))); // NOI18N
        menuJetaudio.setText("JetAudio");
        popRenderAudio1.add(menuJetaudio);
        popRenderAudio1.add(jSeparator1);

        menuBackToMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Misc-Back-icon2.png"))); // NOI18N
        menuBackToMenu.setText("Back To Menu");
        menuBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBackToMenuActionPerformed(evt);
            }
        });
        popRenderAudio1.add(menuBackToMenu);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 71, 71));
        jLabel1.setText("Audio");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        btnWinamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/audio/Winamp-icon.png"))); // NOI18N
        btnWinamp.setToolTipText("Winamp");
        btnWinamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWinampActionPerformed(evt);
            }
        });

        btnAimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/audio/aimp-icon.png"))); // NOI18N
        btnAimp.setToolTipText("Aimp");
        btnAimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAimpActionPerformed(evt);
            }
        });

        btnJetaudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/audio/JetAudio-icon.png"))); // NOI18N
        btnJetaudio.setToolTipText("JetAudio");
        btnJetaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJetaudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnWinamp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAimp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJetaudio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, Short.MAX_VALUE)
                .addGap(159, 159, 159))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJetaudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWinamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void menuBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBackToMenuActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition=new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout=(CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "Menu Dekstop");
    }//GEN-LAST:event_menuBackToMenuActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==MouseEvent.BUTTON3){
            popRenderAudio1.show((Component)evt.getSource(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnWinampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWinampActionPerformed
        // TODO add your handling code here:
        controllerAudio.run("winamp.exe");
    }//GEN-LAST:event_btnWinampActionPerformed

    private void btnAimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAimpActionPerformed
        // TODO add your handling code here:
        controllerAudio.run("AIMP2.exe");
    }//GEN-LAST:event_btnAimpActionPerformed

    private void btnJetaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJetaudioActionPerformed
        // TODO add your handling code here:
        controllerAudio.run("JetAudio.exe");
    }//GEN-LAST:event_btnJetaudioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.view.render.panel.button.Button2 btnAimp;
    private san.jmat.view.render.panel.button.Button2 btnJetaudio;
    private san.jmat.view.render.panel.button.Button2 btnWinamp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuAimp;
    private javax.swing.JMenuItem menuBackToMenu;
    private javax.swing.JMenuItem menuJMat;
    private javax.swing.JMenuItem menuJetaudio;
    private javax.swing.JMenuItem menuWinamp;
    private san.jmat.view.render.panel.popRender.popRenderAudio popRenderAudio1;
    // End of variables declaration//GEN-END:variables
}
