/*
 * |----------------JMat (Java Master)-------------------------------------|
 * |Setiap Manusia Yang Menata Hidupnya adalah Programmer                  |
 * |Hak Cipta Hanya Milik Allah SWT, Hamba-Nya Hanya Memanfaatkan.         |
 * |Manusia Tidak Bisa Mewujudkan Apa-apa, Manusia Hanya Bisa Merencanakan.| 
 * |----------------JMat (Java Master)-------------------------------------| 
 */
package san.jmat.view.render.panel.pack;

import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.BlindVerticalImageTransition;
import com.stripbandunk.jglasspane.transition.image.BoxOutImageTransition;
import com.stripbandunk.jglasspane.transition.image.FadeImageTransition;
import com.stripbandunk.jglasspane.transition.image.FadeRotateImageTransition;
import com.stripbandunk.jglasspane.transition.image.MinimizeHorizontalImageTransition;
import com.stripbandunk.jglasspane.transition.image.SplitHorizontalInImageTransition;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import san.jmat.controler.ControllerExplorer;
import san.jmat.controler.ControllerOffice;
import san.jmat.controler.ControllerWebBrowser;
import san.jmat.model.Office;
import san.jmat.model.WebBrowser;
import san.jmat.model.windowsDefaultAplikasi;
import san.jmat.program.Form;
import san.jmat.view.render.panel.button.Button2;

/**
 *
 * @author joker
 */
public class MenuDesktop extends javax.swing.JPanel {

    private Form form;
    private Office office;
    private ControllerOffice controllerOffice;
    private windowsDefaultAplikasi wDefaultAplikasi;
    private ControllerExplorer controllerExplorer;
    private WebBrowser webBrowser;
    private ControllerWebBrowser controllerWebBrowser;

    /**
     * Creates new form MenuDesktop
     */
    public MenuDesktop() {
        initComponents();
        office = new Office();
        wDefaultAplikasi=new windowsDefaultAplikasi();
        webBrowser=new WebBrowser();
        controllerOffice = new ControllerOffice();
        controllerOffice.setOffice(office);
        controllerExplorer = new ControllerExplorer();
        controllerExplorer.setwDefaultAplikasi(wDefaultAplikasi);
        controllerWebBrowser=new ControllerWebBrowser();
        controllerWebBrowser.setWebBrowser(webBrowser);
        
    }

    public void setForm(Form form) {
        this.form = form;
         
    }

    public Button2 getBtnOffice1() {
        return btnOffice1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOffice1 = new san.jmat.view.render.panel.button.Button2();
        button21 = new san.jmat.view.render.panel.button.Button2();
        btnWebBrowser = new san.jmat.view.render.panel.button.Button2();
        button22 = new san.jmat.view.render.panel.button.Button2();
        button23 = new san.jmat.view.render.panel.button.Button2();
        button31 = new san.jmat.view.render.panel.button.Button3();
        button24 = new san.jmat.view.render.panel.button.Button2();
        jPanel2 = new javax.swing.JPanel();
        lblDekstop = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);

        btnOffice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Office-icon.png"))); // NOI18N
        btnOffice1.setToolTipText("Office Menu");
        btnOffice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffice1ActionPerformed(evt);
            }
        });

        button21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Windows-icon.png"))); // NOI18N
        button21.setToolTipText("Window Explorer");
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });

        btnWebBrowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Apps-web-browser-icon2.png"))); // NOI18N
        btnWebBrowser.setToolTipText("Web Browser");
        btnWebBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebBrowserActionPerformed(evt);
            }
        });

        button22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Video-icon2.png"))); // NOI18N
        button22.setToolTipText("Video");
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });

        button23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Apps-sound-icon.png"))); // NOI18N
        button23.setToolTipText("Audio");
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });

        button31.setToolTipText("Accssesoris");
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button31ActionPerformed(evt);
            }
        });

        button24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Programming-icon2.png"))); // NOI18N
        button24.setToolTipText("IDE");
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(button22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnOffice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(button21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnWebBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOffice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWebBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnOffice1, button22, button23, button24, button31});

        jPanel2.setOpaque(false);

        lblDekstop.setFont(new java.awt.Font("Comic Sans MS", 1, 55)); // NOI18N
        lblDekstop.setForeground(new java.awt.Color(255, 51, 0));
        lblDekstop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDekstop.setText("Shortcut Virtual");
        lblDekstop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDekstopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDekstopMouseExited(evt);
            }
        });
        jPanel2.add(lblDekstop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOffice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffice1ActionPerformed
        // TODO add your handling code here:
        FadeRotateImageTransition transition=new FadeRotateImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "Office Pack");
        controllerOffice.cekekkingPackOffice(form.getOfficePack1());

    }//GEN-LAST:event_btnOffice1ActionPerformed

    private void lblDekstopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDekstopMouseEntered
        // TODO add your handling code here:
        lblDekstop.setText("JAVA MASTER");
        lblDekstop.setForeground(Color.YELLOW);
    }//GEN-LAST:event_lblDekstopMouseEntered

    private void lblDekstopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDekstopMouseExited
        // TODO add your handling code here:
        lblDekstop.setText("Shortcut Virtual");
        lblDekstop.setForeground(Color.RED);
    }//GEN-LAST:event_lblDekstopMouseExited

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        controllerExplorer.runExplorer(this);
    }//GEN-LAST:event_button21ActionPerformed

    private void btnWebBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebBrowserActionPerformed
        // TODO add your handling code here:
        MinimizeHorizontalImageTransition transition=new MinimizeHorizontalImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "Web Browser");
        controllerWebBrowser.cekkingFileExe(form.getBrowser1());
    }//GEN-LAST:event_btnWebBrowserActionPerformed

    private void button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button31ActionPerformed
        // TODO add your handling code here:
        
        
        new Thread(new Runnable() {

            @Override
            public void run() {
                
                final CardLayout cardLayout=(CardLayout) form.getPanelBackground1().getLayout();
            EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                    try {
                        Thread.sleep(300);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MenuDesktop.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    BoxOutImageTransition transition=new BoxOutImageTransition();
                    transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
                    form.getImageTransitionComponent1().setTransition(transition);
                    form.getImageTransitionComponent1().start(1000);
                       cardLayout.show(form.getPanelBackground1(), "accessories");
                    }
                });
            }
        }).start();
        
    }//GEN-LAST:event_button31ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition=new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout=(CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "audio");
    }//GEN-LAST:event_button23ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        // TODO add your handling code here:
        SplitHorizontalInImageTransition transition=new SplitHorizontalInImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(),"video");
    }//GEN-LAST:event_button22ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        // TODO add your handling code here:
        BlindVerticalImageTransition transition=new BlindVerticalImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout=(CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "IDE");
    }//GEN-LAST:event_button24ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.view.render.panel.button.Button2 btnOffice1;
    private san.jmat.view.render.panel.button.Button2 btnWebBrowser;
    private san.jmat.view.render.panel.button.Button2 button21;
    private san.jmat.view.render.panel.button.Button2 button22;
    private san.jmat.view.render.panel.button.Button2 button23;
    private san.jmat.view.render.panel.button.Button2 button24;
    private san.jmat.view.render.panel.button.Button3 button31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDekstop;
    // End of variables declaration//GEN-END:variables
}
