/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package san.jmat.view.render.panel.pack;

import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.FadeRotateImageTransition;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import san.jmat.controler.ControllerVideo;
import san.jmat.program.Form;
import san.jmat.view.render.panel.button.Button2;

/**
 *
 * @author wannabe
 */
public class Video extends javax.swing.JPanel {
    
    private Form form;
    private ControllerVideo controllerVideo;
    /**
     * Creates new form Video
     */
    public Video() {
        initComponents();
        DisableButtonnMenu();
    }
    
    public void setForm(Form form) {
        this.form = form;
    }
    
    public Button2 getButtonGOM() {
        return buttonGOM;
    }
    
    public Button2 getButtonMDP() {
        return buttonMDP;
    }
    
    public Button2 getButtonMPC() {
        return buttonMPC;
    }
    
    public JMenuItem getMenuGOM() {
        return menuGOM;
    }
    
    public JMenuItem getMenuMPC() {
        return menuMPC;
    }
    
    public JMenuItem getMenuWindowsMediaPlayer() {
        return menuWindowsMediaPlayer;
    }
    
    private void DisableButtonnMenu() {
        buttonMDP.setVisible(false);
        menuWindowsMediaPlayer.setVisible(false);
        buttonGOM.setVisible(false);
        menuGOM.setVisible(false);
        buttonMPC.setVisible(false);
        menuMPC.setVisible(false);
    }

    public void setControllerVideo(ControllerVideo controllerVideo) {
        this.controllerVideo = controllerVideo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popRenderVideo1 = new san.jmat.view.render.panel.popRender.popRenderVideo();
        menuJMat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuWindowsMediaPlayer = new javax.swing.JMenuItem();
        menuGOM = new javax.swing.JMenuItem();
        menuMPC = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuBackToMenu = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonMDP = new san.jmat.view.render.panel.button.Button2();
        buttonGOM = new san.jmat.view.render.panel.button.Button2();
        buttonMPC = new san.jmat.view.render.panel.button.Button2();

        menuJMat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuJMat.setText("JMat");
        popRenderVideo1.add(menuJMat);
        popRenderVideo1.add(jSeparator1);

        menuWindowsMediaPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/video/Windows-Media-Player-12-icon1.png"))); // NOI18N
        menuWindowsMediaPlayer.setText("Windows Media Player");
        popRenderVideo1.add(menuWindowsMediaPlayer);

        menuGOM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/video/Apps-GOM-Player-Metro-icon2.png"))); // NOI18N
        menuGOM.setText("GOM");
        popRenderVideo1.add(menuGOM);

        menuMPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/video/bobines-video-icon7.png"))); // NOI18N
        menuMPC.setText("Media Player Classic");
        popRenderVideo1.add(menuMPC);
        popRenderVideo1.add(jSeparator2);

        menuBackToMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuBackToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/Misc-Back-icon2.png"))); // NOI18N
        menuBackToMenu.setText("Back To Menu");
        menuBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBackToMenuActionPerformed(evt);
            }
        });
        popRenderVideo1.add(menuBackToMenu);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 160, 105));
        jLabel1.setText("Video");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        buttonMDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/video/Windows-Media-Player-12-icon.png"))); // NOI18N
        buttonMDP.setToolTipText("Windows Media Player");
        buttonMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMDPActionPerformed(evt);
            }
        });

        buttonGOM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/video/Apps-GOM-Player-Metro-icon.png"))); // NOI18N
        buttonGOM.setToolTipText("GOM");
        buttonGOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGOMActionPerformed(evt);
            }
        });

        buttonMPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/san/jmat/view/render/panel/gambar/video/bobines-video-icon2.png"))); // NOI18N
        buttonMPC.setToolTipText("Media Player Classic");
        buttonMPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(buttonMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGOM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMPC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 109, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            popRenderVideo1.show((Component) evt.getSource(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel2MouseClicked
    
    private void menuBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBackToMenuActionPerformed
        // TODO add your handling code here:
        FadeRotateImageTransition transition = new FadeRotateImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(form.getPanelBackground1(), form.getGlassPane()));
        form.getImageTransitionComponent1().setTransition(transition);
        form.getImageTransitionComponent1().start(1000);
        CardLayout cardLayout;
        cardLayout = (CardLayout) form.getPanelBackground1().getLayout();
        cardLayout.show(form.getPanelBackground1(), "Menu Dekstop");
    }//GEN-LAST:event_menuBackToMenuActionPerformed

    private void buttonMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMDPActionPerformed
        // TODO add your handling code here:
        controllerVideo.Run("wmplayer.exe");
    }//GEN-LAST:event_buttonMDPActionPerformed

    private void buttonGOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGOMActionPerformed
        // TODO add your handling code here:
        controllerVideo.Run("C:\\Program Files\\GRETECH\\GomPlayer\\GOM.exe");
    }//GEN-LAST:event_buttonGOMActionPerformed

    private void buttonMPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMPCActionPerformed
        // TODO add your handling code here:
        controllerVideo.Run("C:\\Program Files\\K-Lite Codec Pack\\Media Player Classic\\mplayerc.exe");
    }//GEN-LAST:event_buttonMPCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.view.render.panel.button.Button2 buttonGOM;
    private san.jmat.view.render.panel.button.Button2 buttonMDP;
    private san.jmat.view.render.panel.button.Button2 buttonMPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuBackToMenu;
    private javax.swing.JMenuItem menuGOM;
    private javax.swing.JMenuItem menuJMat;
    private javax.swing.JMenuItem menuMPC;
    private javax.swing.JMenuItem menuWindowsMediaPlayer;
    private san.jmat.view.render.panel.popRender.popRenderVideo popRenderVideo1;
    // End of variables declaration//GEN-END:variables
}
