/*
 * |----------------JMat (Java Master)-------------------------------------|
 * |Setiap Manusia Yang Menata Hidupnya adalah Programmer                  |
 * |Hak Cipta Hanya Milik Allah SWT, Hamba-Nya Hanya Memanfaatkan.         |
 * |Manusia Tidak Bisa Mewujudkan Apa-apa, Manusia Hanya Bisa Merencanakan.| 
 * |----------------JMat (Java Master)-------------------------------------| 
 */
package san.jmat.program;

import com.stripbandunk.jglasspane.JGlassPane;
import com.stripbandunk.jglasspane.component.ImageTransitionComponent;
import com.stripbandunk.jglasspane.transition.image.creator.ComponentImageCreator;
import san.jmat.controler.ControllerAccessories;
import san.jmat.controler.ControllerAudio;
import san.jmat.controler.ControllerIDE;
import san.jmat.controler.ControllerOffice;
import san.jmat.controler.ControllerVideo;
import san.jmat.controler.ControllerWebBrowser;
import san.jmat.model.ModelIDE;
import san.jmat.model.Office;
import san.jmat.model.WebBrowser;
import san.jmat.model.modelAccessories;
import san.jmat.model.modelAudio;
import san.jmat.model.modelVideo;
import san.jmat.view.render.panel.pack.Browser;
import san.jmat.view.render.panel.pack.MenuDesktop;
import san.jmat.view.render.panel.pack.officePack;
import san.jmat.view.render.panel.panelBackground;

/**
 *
 * @author joker
 */
public class Form extends javax.swing.JFrame {

    private ControllerOffice controllerOffice;
    private Office office;
    private ControllerWebBrowser controllerWebBrowser;
    private WebBrowser webBrowser;
    private ControllerAccessories controllerAccessories;
    private modelAccessories modelAccessories;
    private ControllerAudio controllerAudio;
    private modelAudio modelAudio;
    private modelVideo modelVideo;
    private ControllerVideo controllerVideo;
    private ModelIDE modelIDE;
    private ControllerIDE controllerIDE;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        setSize(650, 480);
        setLocationRelativeTo(null);
        office = new Office();
        controllerOffice = new ControllerOffice();
        controllerOffice.setOffice(office);
        webBrowser=new WebBrowser();
        controllerWebBrowser=new ControllerWebBrowser();
        controllerWebBrowser.setWebBrowser(webBrowser);
        modelAccessories=new modelAccessories();
        controllerAccessories=new ControllerAccessories();
        controllerAccessories.setAccessories(modelAccessories);
        accessories1.setControllerAccessories(controllerAccessories);
        modelAudio=new modelAudio();
        controllerAudio=new ControllerAudio(audio1);
        controllerAudio.setModAudio(modelAudio);
        modelVideo=new modelVideo();
        controllerVideo=new ControllerVideo(video1);
        controllerVideo.setmVideo(modelVideo);
        modelIDE=new ModelIDE();
        controllerIDE=new ControllerIDE(iDE1);
        controllerIDE.setModelIDE(modelIDE);
        
        setGlassPane(jGlassPane1);
        getGlassPane().setVisible(true);
        jGlassPane1.addGlassPaneComponent(imageTransitionComponent1);
        imageTransitionComponent1.setImageCreator(new ComponentImageCreator(panelBackground1));
    }

    public panelBackground getPanelBackground1() {
        return panelBackground1;
    }

    public MenuDesktop getMenuDesktop1() {
        return menuDesktop1;
    }

    public officePack getOfficePack1() {
        return officePack1;
    }

    public Browser getBrowser1() {
        return browser1;
    }

    public ImageTransitionComponent getImageTransitionComponent1() {
        return imageTransitionComponent1;
    }

    public JGlassPane getjGlassPane1() {
        return jGlassPane1;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageTransitionComponent1 = new com.stripbandunk.jglasspane.component.ImageTransitionComponent();
        jGlassPane1 = new com.stripbandunk.jglasspane.JGlassPane();
        panelBackground1 = new san.jmat.view.render.panel.panelBackground();
        menuDesktop1 = new san.jmat.view.render.panel.pack.MenuDesktop();
        officePack1 = new san.jmat.view.render.panel.pack.officePack();
        browser1 = new san.jmat.view.render.panel.pack.Browser();
        accessories1 = new san.jmat.view.render.panel.pack.Accessories();
        audio1 = new san.jmat.view.render.panel.pack.Audio();
        video1 = new san.jmat.view.render.panel.pack.Video();
        iDE1 = new san.jmat.view.render.panel.pack.IDE();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shortcut Virtual");
        setFocusable(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelBackground1.setLayout(new java.awt.CardLayout());
        panelBackground1.add(menuDesktop1, "Menu Dekstop");
        panelBackground1.add(officePack1, "Office Pack");
        panelBackground1.add(browser1, "Web Browser");
        panelBackground1.add(accessories1, "accessories");
        panelBackground1.add(audio1, "audio");
        panelBackground1.add(video1, "video");
        panelBackground1.add(iDE1, "IDE");

        getContentPane().add(panelBackground1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        menuDesktop1.setForm(this);
        officePack1.setForm(this);
        browser1.setForm(this);
        accessories1.setForm(this);
        accessories1.disableButton(controllerAccessories.getCekCalc(), controllerAccessories.getCekMath(), controllerAccessories.getCekNotepad(), controllerAccessories.getCekNotes(), controllerAccessories.getCekPaint(), controllerAccessories.getCekRecorder(), controllerAccessories.getCekWordPad());
        audio1.setForm(this);
        audio1.setControllerAudio(controllerAudio);
        video1.setForm(this);
        video1.setControllerVideo(controllerVideo);
        iDE1.setForm(this);
        iDE1.setControllerIDE(controllerIDE);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private san.jmat.view.render.panel.pack.Accessories accessories1;
    private san.jmat.view.render.panel.pack.Audio audio1;
    private san.jmat.view.render.panel.pack.Browser browser1;
    private san.jmat.view.render.panel.pack.IDE iDE1;
    private com.stripbandunk.jglasspane.component.ImageTransitionComponent imageTransitionComponent1;
    private com.stripbandunk.jglasspane.JGlassPane jGlassPane1;
    private san.jmat.view.render.panel.pack.MenuDesktop menuDesktop1;
    private san.jmat.view.render.panel.pack.officePack officePack1;
    private san.jmat.view.render.panel.panelBackground panelBackground1;
    private san.jmat.view.render.panel.pack.Video video1;
    // End of variables declaration//GEN-END:variables
}
